### PR TITLE
Add Microsoft Copilot

### PR DESCRIPTION
**Pull request by PierreMesure**
This PR adds two documents for Microsoft Copilot:
- the Terms of service
- the Privacy statement.

It's a response to #121.

### CODE REVIEW

**Review by clementbiron — CHANGES_REQUESTED** [review]
Thanks for your suggestion!
I'll need to make a few changes before I can approve it, it's not an easy first contribution and you've done very well.

**Comment by PierreMesure** [comment]
Thank you Clément, changes approved.

**Comment by PierreMesure** [comment]
It got a bit messy with the added comma. If you want, I could squash the commits and make it cleaner but I won't do it tonight, it's too late.

**Review by clementbiron — APPROVED** [review]
Thank you very much Pierre, I think it's very important to follow the Microsoft Copilot documents.

As for your proposal to squash commits, I think it's a bit over-engineered, the commit messages aren't perfect but it's perfectly acceptable to me!

🚀

**Pull request merged**
